train_batch_size: 64
test_batch_size: 256
net: deepsort-reid
data_dir: /home/ha/Downloads/Dataset/VeRi/pytorch
image_shape: [128, 64]  # default image shape
feature_dim: 128  # default feature dimension
device: cpu
resume: false
epochs: 3
save_folder: deepsort-reid-Adam-cosine
optim: Adam
lr: 0.0003
scheduler: cosine
optim: Adam
