train_batch_size: 128
data_dir: /VRU/pytorch
net: osnet_x0_25
image_shape: [128, 128]
feature_dim: 128
device: cpu
resume: false
epochs: 5
save_folder: null
optim: Adam
lr: 0.0003
pretrained: True
scheduler: cosine
pretrained_weight: null
metric_loss: null
