train_batch_size: 128
data_dir: /VRU/pytorch
net: resnet18
image_shape: [128, 128]
feature_dim: 128
device: cpu
resume: false
epochs: 3
save_folder: null
optim: Adam
lr: 0.0003
metric_loss: null
scheduler: cosine
pretrained: False
pretrained_weight: null
